version: 2.1

executors:
  rubypuppet:
    parameters:
      ruby_version:
        type: string
      puppet_gem_version:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby_version >>
    environment:
      PUPPET_GEM_VERSION: << parameters.puppet_gem_version >>

commands:
  runspecs:
    description: "A command for running rake spec"
    parameters:
      spec_command:
        type: string
        #default: "parallel_spec"
    steps:
      - checkout
      - run: bundle -v
      - run: rm -f Gemfile.lock
      - run: gem update --system $RUBYGEMS_VERSION
      - run: gem --version
      - run: bundle -v
      - run: ruby -v | tee ruby_version.txt
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ checksum "ruby_version.txt" }}-{{ checksum "Gemfile" }}-{{ .Environment.CIRCLE_PR_NUMBER }}
            - cache-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ checksum "ruby_version.txt" }}-{{ checksum "Gemfile" }}-
            - cache-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ checksum "ruby_version.txt" }}-
            - cache-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-
      - run: bundle install --jobs $(nproc) --path vendor/bundle
      - run: bundle clean --force
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ checksum "ruby_version.txt" }}-{{ checksum "Gemfile" }}-{{ .Environment.CIRCLE_PR_NUMBER }}
          paths:
            - vendor/bundle
      - run: bundle exec rake << parameters.spec_command >>

jobs:
  run_specs_on_ruby_puppet_combo:
    parameters:
      ruby_version:
        type: string
      puppet_gem_version:
        type: string
      spec_command:
        type: string
    executor:
      name: rubypuppet
      ruby_version: << parameters.ruby_version >>
      puppet_gem_version: << parameters.puppet_gem_version >>
    steps:
      - runspecs:
          spec_command: << parameters.spec_command >>

workflows:
  version: 2
  PDK:
    jobs:
      - run_specs_on_ruby_puppet_combo:
          name: lint
          ruby_version: "2.5.3"
          puppet_gem_version: "~> 6.0"
          spec_command: "check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      - run_specs_on_ruby_puppet_combo:
          name: puppet6specs
          ruby_version: "2.5.3"
          puppet_gem_version: "~> 6.0"
          spec_command: "parallel_spec"
          requires:
            - lint
      - run_specs_on_ruby_puppet_combo:
          name: puppet5specs
          ruby_version: "2.4.5"
          puppet_gem_version: "~> 5.0"
          spec_command: "parallel_spec"
          requires:
            - lint
